package ru.komus.etrnprobe;
import org.junit.Test;
import static org.junit.Assert.*;
import org.json.*;
import java.util.*;

/** Fixtures authored from field tables, not captures from a driver. */
public class ProtocolChecksTest {
    private JSONObject action(String n)throws Exception{return new JSONObject().put("Название",n).put("ТребуетПодписания","Да");}
    private JSONObject stage(String id,JSONArray actions)throws Exception{return new JSONObject().put("Идентификатор",id).put("Действие",actions);}
    private JSONObject doc()throws Exception{return new JSONObject().put("Идентификатор","d1").put("Этап",new JSONArray().put(stage("s1",new JSONArray().put(action("Принят")))));}
    private JSONObject prepared()throws Exception{JSONObject d=doc();d.getJSONArray("Этап").getJSONObject(0).put("Вложение",new JSONArray().put(new JSONObject().put("Идентификатор","f1").put("ТребуемоеДействие","Подписать")));return new JSONObject().put("Документ",d);}
    private JSONObject page(int p,int count,boolean more)throws Exception{JSONArray ds=new JSONArray();for(int i=0;i<count;i++)ds.put(new JSONObject().put("Идентификатор","d"+(p*50+i)).put("Дата","18.09.2026").put("Тип","ConsignmentNote"));return new JSONObject().put("result",new JSONObject().put("Документ",ds).put("Навигация",new JSONObject().put("Страница",String.valueOf(p)).put("ЕстьЕще",more?"Да":"Нет")));}
    @Test public void exactOneSigningActionIsReturned()throws Exception{assertEquals("Принят",ProtocolChecks.onlySigningChoice(doc()).action.getString("Название"));}
    @Test public void twoActionsAreNotScoredByName()throws Exception{JSONObject d=doc();d.getJSONArray("Этап").getJSONObject(0).getJSONArray("Действие").put(action("Не принят"));assertThrows(IllegalArgumentException.class,()->ProtocolChecks.onlySigningChoice(d));}
    @Test public void otherStageDoesNotSupplySignableFiles()throws Exception{JSONObject r=prepared();r.getJSONObject("Документ").getJSONArray("Этап").put(new JSONObject().put("Идентификатор","other").put("Вложение",new JSONArray().put(new JSONObject().put("Идентификатор","wrong").put("ТребуемоеДействие","Подписать"))));assertEquals(Arrays.asList("f1"),ProtocolChecks.signableIds(r,"d1","s1"));}
    @Test public void recursiveDecoyCannotBeSigned()throws Exception{JSONObject r=prepared();r.put("debug",new JSONObject().put("Идентификатор","wrong").put("ТребуемоеДействие","Подписать"));assertEquals(Arrays.asList("f1"),ProtocolChecks.signableIds(r,"d1","s1"));}
    @Test public void responseFromWrongDocumentIsRejected()throws Exception{JSONObject r=prepared();assertThrows(IllegalArgumentException.class,()->ProtocolChecks.signableIds(r,"other","s1"));}
    @Test public void missingStageIsRejected()throws Exception{JSONObject r=prepared();assertThrows(IllegalArgumentException.class,()->ProtocolChecks.signableIds(r,"d1","other"));}
    @Test public void duplicateAttachmentIsNotSilentlyDeduped()throws Exception{JSONObject r=prepared();JSONArray a=r.getJSONObject("Документ").getJSONArray("Этап").getJSONObject(0).getJSONArray("Вложение");a.put(a.getJSONObject(0));assertThrows(IllegalArgumentException.class,()->ProtocolChecks.signableIds(r,"d1","s1"));}
    @Test public void completePaginationReadsThreePages()throws Exception{int[] calls={0};List<JSONObject> d=ProtocolChecks.listByDocumentDate("18.09.2026",q->{int p=Integer.parseInt(q.getJSONObject("Фильтр").getJSONObject("Навигация").getString("Страница"));assertEquals("18.09.2026",q.getJSONObject("Фильтр").getString("ДатаС"));assertFalse(q.getJSONObject("Фильтр").has("ДатаВремяС"));calls[0]++;return page(p,p<2?50:20,p<2);});assertEquals(120,d.size());assertEquals(3,calls[0]);}
    @Test public void missingNavigationNeverMeansCompleteList()throws Exception{assertThrows(IllegalArgumentException.class,()->ProtocolChecks.listByDocumentDate("18.09.2026",q->new JSONObject().put("result",new JSONObject().put("Документ",new JSONArray()))));}
    @Test public void repeatedPageIsBlocked()throws Exception{assertThrows(IllegalArgumentException.class,()->ProtocolChecks.listByDocumentDate("18.09.2026",q->page(0,50,true)));}
    @Test public void wrongDocumentDateIsRejected()throws Exception{assertThrows(IllegalArgumentException.class,()->ProtocolChecks.listByDocumentDate("17.09.2026",q->page(0,1,false)));}
    @Test public void invalidCalendarDateDoesNotCallTransport()throws Exception{assertThrows(java.time.DateTimeException.class,()->ProtocolChecks.listByDocumentDate("31.02.2026",q->{fail("network called");return null;}));}
    @Test public void twoFactorCanParseStringifiedAddinfo()throws Exception{String a="{\"Идентификатор\":\"challenge\",\"SessionID\":\"temp\"}";JSONObject e=new JSONObject().put("error",new JSONObject().put("data",new JSONObject().put("addinfo",a)));assertEquals("temp",ProtocolChecks.twoFactor(e).getString("session"));}
    @Test public void arbitraryNestedIdentifierIsNotChallenge()throws Exception{JSONObject e=new JSONObject().put("debug",new JSONObject().put("Идентификатор","wrong").put("SessionID","temp"));assertEquals(0,ProtocolChecks.twoFactor(e).length());}
    @Test public void rpcResponseMustMatchRequestId()throws Exception{JSONObject q=new JSONObject().put("id",1),r=new JSONObject().put("id",2).put("jsonrpc","2.0").put("result","ok");assertThrows(IllegalArgumentException.class,()->ProtocolChecks.validateEnvelope(q,r));}
    @Test public void resultAndErrorCannotBothBePresent()throws Exception{JSONObject q=new JSONObject().put("id",1),r=new JSONObject().put("id",1).put("jsonrpc","2.0").put("result","ok").put("error",new JSONObject());assertThrows(IllegalArgumentException.class,()->ProtocolChecks.validateEnvelope(q,r));}
    @Test public void rawHtmlEnvelopeIsNotSuccess()throws Exception{JSONObject q=new JSONObject().put("id",1),r=new JSONObject().put("raw","<html>bad gateway</html>");assertThrows(IllegalArgumentException.class,()->ProtocolChecks.validateEnvelope(q,r));}
    @Test public void finalizationPinsRevisionAndStage()throws Exception{BatchEngine.Document d=new BatchEngine.Document("d1","r1","s1","Принят","p");BatchEngine.Signature s=new BatchEngine.Signature("d1","f1","hash","p",new byte[]{1,2,3});JSONObject p=ProtocolChecks.finalization(d,Arrays.asList(s)).getJSONObject("Документ");assertFalse(p.has("Идентификатор"));assertEquals("r1",p.getJSONObject("Редакция").getString("Идентификатор"));assertEquals("s1",p.getJSONObject("Этап").getString("Идентификатор"));assertEquals(1,p.getJSONObject("Этап").getJSONArray("Действие").length());assertEquals("AQID",p.getJSONObject("Этап").getJSONArray("Вложение").getJSONObject(0).getJSONArray("Подпись").getJSONObject(0).getJSONObject("Файл").getString("ДвоичныеДанные"));}
    @Test public void finalizationCannotAttachOtherDocumentSignature()throws Exception{BatchEngine.Document d=new BatchEngine.Document("d1","r1","s1","Принят","p");BatchEngine.Signature s=new BatchEngine.Signature("d2","f2","hash","p",new byte[]{1});assertThrows(IllegalArgumentException.class,()->ProtocolChecks.finalization(d,Arrays.asList(s)));}
}
