plugins { id 'com.android.application' }
android {
    namespace 'ru.komus.etrnprobe'
    compileSdk 35
    defaultConfig {
        applicationId 'ru.komus.etrnprobe'
        minSdk 26
        targetSdk 35
        versionCode 4
        versionName '2.2-r2-fix2'
    }
    buildTypes { release { minifyEnabled false } }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
dependencies {
    testImplementation 'junit:junit:4.13.2'
    testImplementation 'org.json:json:20240303'
}
